version: '3.4'

networks:
  mealforfamily-dev:
    driver: bridge 

services:
  mealforfamily:
    image: mealforfamily:latest
    depends_on:
      - "postgres"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres;port=5432;database=mealforfamilydb;username=test;password=test"
    networks:
      - mealforfamily-dev  
  
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "mealforfamilydb"
    networks:
      - mealforfamily-dev
volumes:
  db_volume: