export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const GET_DONATIONS = "GET_DONATIONS";
export const DELETE_DONATION = "DELETE_DONATION";

export const GET_VOLUNTEER_ACTIONS = "GET_VOLUNTEER_ACTIONS";
export const GET_VOLUNTEER_ACTIONS_STATUSES = "GET_VOLUNTEER_ACTIONS_STATUSES";
export const ADD_ACTION_STATUS = "ADD_ACTION_STATUS";

export const GET_VOLUNTEER_ACTION_TYPES = "GET_VOLUNTEER_ACTION_TYPES";
export const DELETE_VOLUNTEER_ACTION_TYPE = "DELETE_VOLUNTEER_ACTION_TYPE";
export const ADD_VOLUNTEER_ACTION_TYPE = "ADD_VOLUNTEER_ACTION_TYPE";
export const UPDATE_VOLUNTEER_ACTION_TYPE = "UPDATE_VOLUNTEER_ACTION_TYPE";

export const GET_CONTACTS = "GET_CONTACTS";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const ADD_CONTACT = "ADD_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";

export const GET_BANK_ACCOUNT = "GET_BANK_ACCOUNT";
export const UPDATE_BANK_ACCOUNT = "UPDATE_BANK_ACCOUNT";

export const GET_ABOUT_US = "GET_ABOUT_US";
export const UPDATE_ABOUT_US = "UPDATE_ABOUT_US";
