export enum AppRoute {
  ACTIONS_NAVIGATOR = 'ACTIONS_NAVIGATOR',
  ACTIONS_LIST_SCREEN = 'ACTIONS_LIST_SCREEN',
  ACTION_SCREEN = 'ACTION_SCREEN',
  NEWS_NAVIGATOR = 'NEWS_NAVIGATOR',
  NEWS_LIST_SCREEN = 'NEWS_LIST_SCREEN',
  NEWS_SCREEN = 'NEWS_SCREEN',
  DONATE_SCREEN = 'DONATE_SCREEN',
  ABOUT_US_SCREEN = 'ABOUT_US_SCREEN',
  CONTACT_SCREEN = 'CONTACT_SCREEN',
  ONBOARDING_SCREEN = 'ONBOARDING_ SCREEN',
  TAB_NAVIGATOR = 'TAB_NAVIGATOR',
}
